title: meshkit
description: A utility for MEEG studies for visualising group averaged meshs as videos and more.
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
